### ISSUE TITLE
Buffer on live streaming

### ISSUE THREAD

**Issue by filipepipeline** [teodorpatras/Jukebox#1]
Hey guys.

First of all, congrats for this framework.

Well, when are you guys planning to include the buffer feature on live streaming.

**Comment by teodorpatras** [comment]
it is supported, check the example project

**Comment by filipepipeline** [comment]
How can i apply this, is there a documentation for this option? I did not find on the example. sorry

**Comment by teodorpatras** [comment]
in the example project you'll see that the first item in the playlist is a `m3u` url. pass your url when creating the `JukeboxItem`
