### ISSUE TITLE
Repeat song track

### ISSUE THREAD

**Issue by hirenspaceo** [teodorpatras/Jukebox#12]
Hello Sir,
 is it possible to repeat any track ?
i want to repeat my track for some time

**Comment by glennposadas** [comment]
I think you will be the responsible one to do that (the repeat functionality). :)

**Comment by teodorpatras** [comment]
It is easy to do the repeating functionality, you have the delegation methods where you can manually replay the track at a certain index.

**Comment by hirenspaceo** [comment]
Yes you are right but i do change in following function when song end and it is perfectly work fo
`func playerItemDidPlayToEnd(notification : NSNotification)
    {
        if NSUserDefaults.standardUserDefaults().valueForKey("isRepeatTrack") as! String == "on"
        {
            self.player!.seekToTime(kCMTimeZero)
            self.player!.play()
        }
        else
        {
            if playIndex >= self.queuedItems.count - 1
            {
                stop()
            }
            else
            {
                playAtIndex(self.playIndex + 1)
            }
        }   
    }
`

And thank you very much for your reply :)
