### ISSUE TITLE
change jukebox.state == .Loading when airport mode is switched on

### ISSUE THREAD

**Issue by alexrmacleod** [teodorpatras/Jukebox#13]

**Comment by alexrmacleod** [comment]
any luck with this?

**Comment by teodorpatras** [comment]
Unfortunately I did not get the time so far. I will try to fix it this month but I cannot promise. If you want, you can help by making a pr, I can guide you through the changes if something is not right.

**Comment by teodorpatras** [comment]
Fixed in `v0.1.4`, the state will change to `.Failed` and the `Jukebox` will stop playing.

**Comment by alexrmacleod** [comment]
👍 💯

**Comment by alexrmacleod** [comment]
@teodorpatras do you mean v0.1.4? https://github.com/teodorpatras/Jukebox/releases

**Comment by teodorpatras** [comment]
yes, corrected the typo, I recommend you update to the latest version to have all the fixes and features available
