### ISSUE TITLE
how to stream local file?

### ISSUE THREAD

**Issue by jamalalayq** [teodorpatras/Jukebox#17]

**Comment by teodorpatras** [comment]
use `NSBundle`'s `pathForResource:ofType:` 
https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSBundle_Class/#//apple_ref/occ/instm/NSBundle/pathForResource:ofType:

**Comment by jamalalayq** [comment]
Do it

**Comment by syrakozz** [comment]
like this right ?

 let path = NSBundle.mainBundle().pathForResource("2514", ofType:"mp3")

```
    var juk =   JukeboxItem(URL: NSURL(string: path!)!)

    let  jukebox = Jukebox(delegate: self, items: [
  juk
        ])


    jukebox?.play()
```

its not working

**Comment by teodorpatras** [comment]
https://developer.apple.com/reference/foundation/bundle/1411540-url
