### ISSUE TITLE
How to play local song - part 2.

### ISSUE THREAD

**Issue by trieulieuf9** [teodorpatras/Jukebox#18]
You suggest using NSBundle's pathForResource:ofType: 

But i still not know how to use it. Can you give some more details, like how to stick NSBundle into Jukebox.

**Comment by teodorpatras** [comment]
Just create a `JukeBoxItem` with the output from the method I wrote you in the previous opened issue. That method returns an `NSURL`, pass that `NSURL` to the `JukeBoxItem` initializer.

**Comment by syrakozz** [comment]
no working

**Comment by RajChanchal** [comment]
Wanted to play a file saved into my Application Support directory. 
FilePath looks like: `file:///var/mobile/Containers/Data/Application/25DECD8C-BEE9-49B4-8F63-B210391485C3/Library/Application%20Support/u1b1qeh7gIc4zr24CzlhA7dtrHT3dC6n.mp3`
Following is the code that adds `JukeboxItem`to `jukeboxPlaylist`

```
let filePath:URL = URL.init(fileURLWithPath: songObj.filePath!, isDirectory: false)
jukeboxPlaylist.add(JukeboxItem.init(URL: filePath))
```

And it doesn't play it, any suggestion? A remote URL work fine, though.

**Comment by teodorpatras** [comment]
You should check if the file exists at the specified path.

**Comment by RajChanchal** [comment]
I don't think NSBundle can find the Application Support directory as it exists in Sandbox of an app. I have used NSBundle for getting urls of the files that are added in bundle or folders that are apparent in the source directory. What is your say?

**Comment by KushThakkar** [comment]
Same Issue How can I slove?
