### ISSUE TITLE
Need for checkItemAlreadyExists?

### ISSUE THREAD

**Issue by antiero** [teodorpatras/Jukebox#2]
Hey, loving the Jukebox code! 

Just wondering what the reasoning is for not permitting the same track to exist more than once in the queue? Seems like adding a track more than once to a play list might be something people would want to do?

Cheers,
Ant

**Comment by teodorpatras** [comment]
Hey, thanks for the appreciation. Change request implemented in latest Cocoapods release. 

Cheers,
Teodor
