### ISSUE TITLE
[Question] in function configureAudioSession

### ISSUE THREAD

**Issue by AnnieNinaJoyceV** [teodorpatras/Jukebox#20]
Hello, thank you for creating this library. We are using this in one of our app.

```
private func configureAudioSession() {
do {
            try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback)
            try AVAudioSession.sharedInstance().setActive(true)
        } catch {
            fatalError("Could not open the audio session, hence Jukebox is unusable!")
        }
    }
```

I received a crash report from Fabric in this method. So, I was wondering why to use fatalError? And what will happen if we simply update this code to something like this?

```
private func configureAudioSession() {
        try! AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback)
        try! AVAudioSession.sharedInstance().setActive(true)
    }`
```

If you can, please explain what will happen, thanks again for your work.

**Comment by teodorpatras** [comment]
You are right, `fatalError` might be too much, but `try!` will also crash your app if an exception is thrown. Let me come up with a more cleaner solution

**Comment by AnnieNinaJoyceV** [comment]
@teodorpatras Thank you. 👍

**Comment by teodorpatras** [comment]
🎉  `v1.0.4` released! 

now the initializer for `Jukebox` is failable, it will only fail if `Jukebox` cannot open an audio session.  Cheers!
