### ISSUE TITLE
Swift 3 Compatibility

### ISSUE THREAD

**Issue by ZiadAli** [teodorpatras/Jukebox#34]
Does the current version of Jukebox work with Swift 3? I know the commits say that it does, but I keep getting the “Use Legacy Swift Language Version” (SWIFT_VERSION) error whenever I try to compile. Any ideas?

**Comment by mattwritescode** [comment]
I had the same issue, but I've also had that happen with every code repository and library I've added to my projects this month. I think this is XCode being the IDE equivalent of a helicopter parent.
Just let XCode do it's nonsense "Swift 3" conversion. It doesn't change anything of note. ;-)

**Comment by teodorpatras** [comment]
I just tested with a Podfile of only `pod 'Jukebox'` and it works.  Check the Readme file for how to integrate it.
