### ISSUE TITLE
Audio is taking a long time to start playing

### ISSUE THREAD

**Issue by ojoaomorais** [teodorpatras/Jukebox#39]
Hello,all works fine in my player, but when i call jukebox.play() , the player is taking a long time to begin playing.how reduce this time??

**Comment by teodorpatras** [comment]
`Jukebox` uses the standard `AVPlayer`, which has the buffering feature built-in. It might take so much because of the internet connection or other factors.

**Comment by RajChanchal** [comment]
@teodorpatras How can we know if it is buffering, so that we can show relevant loading indicator?
Not on start only, we do usually need to show the loading indicator when internet goes slow and song goes to buffering state. Is there any way to get to know?
