### ISSUE TITLE
error occur in JukeboxItem.swift, line 116

### ISSUE THREAD

**Issue by jidanyu** [teodorpatras/Jukebox#7]
I meet a strange error just happened a special url. 
Here are three mp3 url waitting for play.
 [
"http://dingdong.sosys.cn:8080/uploads/course/107/0/audio.mp3",
"http://dingdong.sosys.cn:8080/uploads/course/107/1/audio.mp3",
"http://dingdong.sosys.cn:8080/uploads/course/107/2/audio.mp3"]

error only occurs when jukebox loaditem which has the second urlString("http://dingdong.sosys.cn:8080/uploads/course/107/1/audio.mp3").

Really ,I have no idea about this, could anyone who has some idea can guide me a way to figure this out?

**Comment by teodorpatras** [comment]
new version released, check if the crash is still reproducing
