### ISSUE TITLE
Player resumes on its own 

### ISSUE THREAD

**Issue by madlyn** [teodorpatras/Jukebox#75]
I'm Using Jukebox to stream audio from a server. Whenever the app is paused and in the background and I get a notification from another source. It starts playing on its own! What can I do to stop that?

**Comment by RajChanchal** [comment]
Hi @madlyn , I have already resolved this issue here: https://github.com/RajChanchal/Jukebox

**Comment by madlyn** [comment]
@RajChanchal works like a charm! Thank you!
