### ISSUE TITLE
Real device bug

### ISSUE THREAD

**Issue by danialepaco** [teodorpatras/Jukebox#84]
When I use my app on emulator works really perfect but on a real device is very slow... anybody with the same issue??

**Comment by vivekathilkar** [comment]
Yes I am facing same issue with this library 
Have You found any solution on this ?

**Comment by danialepaco** [comment]
let url = URL(string: canciones[currentSong].url)
        playerItem = AVPlayerItem(url: url!)
        player = AVPlayer(playerItem: playerItem)
        self.player?.automaticallyWaitsToMinimizeStalling = false
        self.playerItem?.preferredForwardBufferDuration = 0

This the objects I use its different from this library but it will help you, I use AVPlayer object.. the trick is use these two lines in that object jukebox use the same object

self.player?.automaticallyWaitsToMinimizeStalling = false
self.playerItem?.preferredForwardBufferDuration = 0

And that it your music should start immediately... its beacuase AVPlayer by defect download the whole file, that why we set “automaticallyWaitsToMinimizeStalling“ to false

**Comment by bcmdevteam** [comment]
thanks for quick reply.
But, it is not working for me. It takes longer time to load audio file. real device stuck when I changes audio file

**Comment by vivekathilkar** [comment]
Thanks for quick reply.
But it's not working for me.Takes longer timer to load audio file on real device. device stuck when I changes audio
Thanks
